# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 388)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 601, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.zamButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.zamButton.setObjectName("zamButton")
        self.gridLayout.addWidget(self.zamButton, 6, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 4, 2)
        self.smallButton = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.smallButton.setObjectName("smallButton")
        self.gridLayout.addWidget(self.smallButton, 1, 0, 1, 1)
        self.largeButton = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.largeButton.setObjectName("largeButton")
        self.gridLayout.addWidget(self.largeButton, 1, 2, 1, 1)
        self.szyButton = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.szyButton.setObjectName("szyButton")
        self.gridLayout.addWidget(self.szyButton, 3, 2, 1, 1)
        self.pieButton = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.pieButton.setObjectName("pieButton")
        self.gridLayout.addWidget(self.pieButton, 2, 2, 1, 1)
        self.mediumButton = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.mediumButton.setObjectName("mediumButton")
        self.gridLayout.addWidget(self.mediumButton, 1, 1, 1, 1)
        self.anaButton = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.anaButton.setObjectName("anaButton")
        self.gridLayout.addWidget(self.anaButton, 5, 2, 1, 1)
        self.kukButton = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.kukButton.setObjectName("kukButton")
        self.gridLayout.addWidget(self.kukButton, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Wybierz rozmiar pizzy"))
        self.zamButton.setText(_translate("Dialog", "Zamow"))
        self.label_2.setText(_translate("Dialog", "Wybierz dodatki"))
        self.smallButton.setText(_translate("Dialog", "Mala"))
        self.largeButton.setText(_translate("Dialog", "Duza"))
        self.szyButton.setText(_translate("Dialog", "Szynka"))
        self.pieButton.setText(_translate("Dialog", "Pieczarki"))
        self.mediumButton.setText(_translate("Dialog", "Srednia"))
        self.anaButton.setText(_translate("Dialog", "Ananas"))
        self.kukButton.setText(_translate("Dialog", "Kukurydza"))
